<?php
/**
 * Created by PhpStorm.
 * User: michal
 * Date: 19.11.18
 * Time: 09:55
 *
 * @var $product_object WC_Product
 */

wp_nonce_field( 'save_product_package_tab' ,'product_package_tab_nonce' );
$package_products = $product_object->get_meta('_nt_package_product', false);
?>

<div class="options_group">
    <p class="form-field">
        <label for="package_product"><?php esc_html_e( 'Wyszukaj produkt', 'elazienki' ); ?></label>
        <select class="wc-product-search" style="width: 50%;" id="package_product" data-placeholder="<?php esc_attr_e( 'Search for a product&hellip;', 'woocommerce' ); ?>" data-action="woocommerce_json_search_products_and_variations" data-exclude="<?php echo intval( $post->ID ); ?>"></select>
        <a href="" class="button js-add-new-product" style="margin-left: 10px;">Dodaj produkt do zestawu</a>
    </p>
    <div class="js-package-container">
        <?php if(!empty($package_products)) : ?>
            <?php foreach($package_products as $package_product): ?>
                <?php $pd = $package_product->value; ?>
		        <?php $product = wc_get_product($pd['product']); ?>
                <?php if(!empty($product)) : ?>
                    <p class="form-field _package_products_field" data-element="product" data-id="<?= $pd['product']; ?>">
                        <label for="_package_products_field_<?= $pd['product']; ?>" style="width: 350px;"><?= $product->get_name(); ?></label>
                        <input class="short wc_input_decimal" name="_package_products_field[<?= $pd['product']; ?>]" id="_package_products_field_<?= $pd['product']; ?>" value="<?= $pd['amount']; ?>" type="number"/>
                        <a href="" class="js-remove-product" style="color: #ff0000; margin-left: 10px;">Usuń</a>
                    </p>
                <?php endif; ?>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
</div>
<script>
    jQuery(document).ready(function ($) {
        $('.js-add-new-product').on('click', function(e){
            e.preventDefault();
            var value = $('#package_product').val();
            var text = $('#package_product').find('option:selected').html();
            if(typeof value !== 'undefined' && value !== ''){
                var ex = $('.js-package-container').find('[data-id="'+value+'"]');
                if(ex.length == 0) {
                    var $div = $('<p></p>', {
                        class: 'form-field _package_products_field',
                        'data-element': 'product',
                        'data-id': value
                    }).append(
                        $('<label>', {
                            for: '_package_products_field_' + value,
                            text: text,
                            style: 'width: 350px;'
                        })
                    ).append(
                        $('<input>', {
                            class: 'short wc_input_decimal',
                            name: '_package_products_field[' + value + ']',
                            id: '_package_products_field_' + value,
                            type: 'number',
                            value: 1,
                            min: 1,
                        })
                    ).append(
                        $('<a></a>', {
                            class: 'js-remove-product',
                            style: 'color: #ff0000;margin-left: 10px;',
                            href: '',
                            text: 'Usuń'
                        })
                    );
                    $('.js-package-container').append($div);
                }
            }

        });
        $('.js-package-container').on('click', '.js-remove-product', function(e){
            e.preventDefault();
            $(this).parent().remove();
        })
    })
</script>